app/routes.php
<?php

// This 'view composers' will be moved into their own include file eventually but for speed I'm just added them here for now!
View::composer('*', function($view) {
            if (Auth::user()) {
                $view->with('useraccount', $useraccount = \User::find(\Auth::user()));
            }

            // Make the current system version avaliable to all pages.
            $view->with('turbineversion', Setting::getSetting('version'));
        });


// Application routes
Route::resource('/', 'OverviewController', array('only' => array('index')));
Route::resource('rules', 'RulesController');
Route::resource('settings', 'SettingsController', array('only' => array('index', 'store')));
Route::get('logout', array('as' => 'logout', function() {
        Session::flush();
        Auth::logout();
        return Redirect::route('.index');
    }));

app/views/includes/copyright.blade.php
<footer>
    <p>&copy; Turbine Project, 2013. <a href="http://bobsta63.github.io/turbine/" target="_blank">Turbine</a> is written by <a href="http://www.bobbyallen.me" target="_blank">Bobby Allen</a> and released under the <a href="http://opensource.org/licenses/MIT">MIT license</a>.</p>
</footer>

app/views/includes/flashmsgs.blade.php
{{-- This include handles the display of notice, infomation and error notices --}}
@if (Session::has('flash_error'))
<div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Error!</strong> {{ Session::get('flash_error') }}
</div>
<br />
@endif

@if (Session::has('flash_notice'))
<div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Warning!</strong> {{ Session::get('flash_notice') }}
</div>
<br />
@endif

@if (Session::has('flash_info'))
<div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Info!</strong> {{ Session::get('flash_info') }}
</div>
@endif

@if (Session::has('flash_success'))
<div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Success!</strong> {{ Session::get('flash_success') }}
</div>
@endif

app/views/includes/footer.blade.php
<!-- Placed at the end of the document so the pages load faster -->
<script src="js/jquery.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/holder.js"></script>

app/views/includes/head.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.png">
    <title>{{{ $title }}} - Turbine (v.{{{ $turbineversion }}})</title>
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/bootstrap-theme.min.css" rel="stylesheet">
    <link href="css/theme.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
</head>

app/views/includes/navbar.blade.php
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ URL::route('.index') }}">Turbine</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @if(Request::segment(1) == '')
                <li class="active"><a href="{{ URL::route('.index') }}">Overview</a></li>
                @else
                <li><a href="{{ URL::route('.index') }}">Overview</a></li>
                @endif
                @if(Request::segment(1) == 'rules')
                <li class="active"><a href="{{ URL::route('rules.index') }}">Sites &amp; Servers</a></li>
                @else
                <li><a href="{{ URL::route('rules.index') }}">Sites &amp; Servers</a></li>
                @endif
                @if(Request::segment(1) == 'settings')
                <li class="active"><a href="{{ URL::route('settings.index') }}">Settings</a></li>
                @else
                <li><a href="{{ URL::route('settings.index') }}">Settings</a></li>
                @endif
                <li><a href="{{ URL::route('logout') }}">Logout</a></li>
            </ul>
        </div>
    </div>
</div>