app/routes.php
<?php

// This 'view composers' will be moved into their own include file eventually but for speed I'm just added them here for now!
View::composer('*', function($view) {
            if (Auth::user()) {
                $view->with('useraccount', $useraccount = \User::find(\Auth::user()));
            }

            // Make the current system version avaliable to all pages.
            $view->with('turbineversion', Setting::getSetting('version'));
        });


// Application routes
Route::resource('/', 'OverviewController', array('only' => array('index')));
Route::resource('rules', 'RulesController');
Route::resource('settings', 'SettingsController', array('only' => array('index', 'store')));
Route::get('logout', array('as' => 'logout', function() {
        Session::flush();
        Auth::logout();
        return Redirect::route('.index');
    }));

app/views/overview.blade.php
<!DOCTYPE html>
<html lang="en">
    @include('includes/head')
    <body>
        @include('includes/navbar', array('title' => $title))
        @include('includes/flashmsgs')
        <!-- Start of content -->
        <div class="container theme-showcase">
            <div class="jumbotron">
                <div class="container">
                    <p>This appliance is currently running version <strong>{{{ $turbineversion }}}</strong> of Turbine, it has <Strong>{{{ $rulestotal }}}</strong> <a href="{{ URL::route('rules.index') }}">reverse proxy rules</a> configured, <strong>{{{ $rulesnlbtotal }}}</strong> of which are configured using network load-balancing. This server is running <strong>{{ $os }}</strong>.</p>
                </div>
            </div>
            @include('includes/copyright')
        </div>
        <!-- End content -->

        @include('includes/footer')
    </body>
</html>

app/views/rules.blade.php
<!DOCTYPE html>
<html lang="en">
    @include('includes/head')
    <body>
        @include('includes/navbar')

        <!-- Start of content -->
        <div class="container theme-showcase">

            <div class="page-header">
                <h1>Rules</h1>
            </div>
            @include('includes/flashmsgs')

            <h2>Existing rules</h2>
            @if($rules->count()>0)
            <table class="table table-hover">
                <tr><th>Host header</th><th>Enabled</th><th>Target(s)</th><th>Load-balanced</th><th></th></tr>
                @foreach($rules as $rule)
                <tr><td>{{{ $rule->hostheader }}}</td><td>@if($rule->enabled)<span class="glyphicon glyphicon-ok"></span>@endif</td><td>To be loaded from file!</td><td>@if($rule->nlb)<span class="glyphicon glyphicon-ok"></span>@endif</td><td><a href="{{{ URL::route('rules.edit', $rule->id) }}}" class="btn btn-xs btn-default">Edit</a></td></tr>
                @endforeach
            </table>
            @else
            <p>&nbsp;</p>
            <p>There are currently no rules configured on this appliance!</p>
            <p>&nbsp;</p>
            @endif
            <h2>Create new rule</h2>
            {{ Form::open(array('route' => 'rules.store', 'action' => 'POST', 'role' => 'form')) }}
            <div class="form-group">
                <label for="origin_address">Origin address (Host header)</label>
                <input type="text" class="form-control" name="origin_address" id="origin_address" placeholder="eg. www.mydomain.com or *.mydomain.com">
            </div>
            <div class="form-group">
                <label for="target_address">Target server</label>
                <input type="text" class="form-control" name="target_address" id="target_address" placeholder="eg. 192.168.0.12 or web1.internal.local:8080">
                <p class="help-block">You can add multiple target servers (a network load-balanced set-up) after you create this initial rule using the 'edit' button below.</p>
            </div>
            <div class="checkbox">
                <label>
                    <input name="enabled" id="enabled" type="checkbox" checked="checked"> Enabled
                </label>
            </div>
            {{ Form::submit('Create rule', array('class' => 'btn btn-default')) }}
            {{ Form::close() }}
        </form>
        <p>&nbsp;</p>
        @include('includes/copyright')
    </div>
    <!-- End content -->

    @include('includes/footer')
</body>
</html>

app/views/settings.blade.php
<!DOCTYPE html>
<html lang="en">
    @include('includes/head')
    <body>
        @include('includes/navbar')

        <!-- Start of content -->
        <div class="container theme-showcase">

            <div class="page-header">
                <h1>Settings</h1>
            </div>
            @include('includes/flashmsgs')
            {{ Form::open(array('route' => 'settings.store', 'action' => 'POST', 'role' => 'form')) }}
            @foreach($settings as $setting)
            <div class="form-group">
                <label for="{{ $setting->name }}">{{{ $setting->friendlyname }}}</label>
                <input type="text" class="form-control" name="{{ $setting->name }}" id="{{ $setting->name }}" placeholder="eg. www.mydomain.com or *.mydomain.com"@if($setting->svalue) value="{{{ $setting->svalue }}}"@endif>
                       <p class="help-block">{{{ $setting->description }}}</p>
            </div>
            @endforeach
            <!-- End of options -->
            {{ Form::submit('Save changes', array('class' => 'btn btn-default')) }}
            {{ Form::close() }}
        </form>
        <p>&nbsp;</p>
        @include('includes/copyright')
    </div>
    <!-- End content -->

    @include('includes/footer')
</body>
</html>